
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Setlist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Setlist
 * 
 */
export type SetlistModel = runtime.Types.Result.DefaultSelection<Prisma.$SetlistPayload>

export type AggregateSetlist = {
  _count: SetlistCountAggregateOutputType | null
  _avg: SetlistAvgAggregateOutputType | null
  _sum: SetlistSumAggregateOutputType | null
  _min: SetlistMinAggregateOutputType | null
  _max: SetlistMaxAggregateOutputType | null
}

export type SetlistAvgAggregateOutputType = {
  duration: number | null
}

export type SetlistSumAggregateOutputType = {
  duration: number | null
}

export type SetlistMinAggregateOutputType = {
  id: string | null
  slug: string | null
  date: Date | null
  location: string | null
  name: string | null
  duration: number | null
}

export type SetlistMaxAggregateOutputType = {
  id: string | null
  slug: string | null
  date: Date | null
  location: string | null
  name: string | null
  duration: number | null
}

export type SetlistCountAggregateOutputType = {
  id: number
  slug: number
  date: number
  location: number
  name: number
  duration: number
  _all: number
}


export type SetlistAvgAggregateInputType = {
  duration?: true
}

export type SetlistSumAggregateInputType = {
  duration?: true
}

export type SetlistMinAggregateInputType = {
  id?: true
  slug?: true
  date?: true
  location?: true
  name?: true
  duration?: true
}

export type SetlistMaxAggregateInputType = {
  id?: true
  slug?: true
  date?: true
  location?: true
  name?: true
  duration?: true
}

export type SetlistCountAggregateInputType = {
  id?: true
  slug?: true
  date?: true
  location?: true
  name?: true
  duration?: true
  _all?: true
}

export type SetlistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Setlist to aggregate.
   */
  where?: Prisma.SetlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Setlists to fetch.
   */
  orderBy?: Prisma.SetlistOrderByWithRelationInput | Prisma.SetlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SetlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Setlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Setlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Setlists
  **/
  _count?: true | SetlistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SetlistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SetlistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SetlistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SetlistMaxAggregateInputType
}

export type GetSetlistAggregateType<T extends SetlistAggregateArgs> = {
      [P in keyof T & keyof AggregateSetlist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSetlist[P]>
    : Prisma.GetScalarType<T[P], AggregateSetlist[P]>
}




export type SetlistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SetlistWhereInput
  orderBy?: Prisma.SetlistOrderByWithAggregationInput | Prisma.SetlistOrderByWithAggregationInput[]
  by: Prisma.SetlistScalarFieldEnum[] | Prisma.SetlistScalarFieldEnum
  having?: Prisma.SetlistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SetlistCountAggregateInputType | true
  _avg?: SetlistAvgAggregateInputType
  _sum?: SetlistSumAggregateInputType
  _min?: SetlistMinAggregateInputType
  _max?: SetlistMaxAggregateInputType
}

export type SetlistGroupByOutputType = {
  id: string
  slug: string
  date: Date
  location: string
  name: string | null
  duration: number | null
  _count: SetlistCountAggregateOutputType | null
  _avg: SetlistAvgAggregateOutputType | null
  _sum: SetlistSumAggregateOutputType | null
  _min: SetlistMinAggregateOutputType | null
  _max: SetlistMaxAggregateOutputType | null
}

export type GetSetlistGroupByPayload<T extends SetlistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SetlistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SetlistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SetlistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SetlistGroupByOutputType[P]>
      }
    >
  >



export type SetlistWhereInput = {
  AND?: Prisma.SetlistWhereInput | Prisma.SetlistWhereInput[]
  OR?: Prisma.SetlistWhereInput[]
  NOT?: Prisma.SetlistWhereInput | Prisma.SetlistWhereInput[]
  id?: Prisma.StringFilter<"Setlist"> | string
  slug?: Prisma.StringFilter<"Setlist"> | string
  date?: Prisma.DateTimeFilter<"Setlist"> | Date | string
  location?: Prisma.StringFilter<"Setlist"> | string
  name?: Prisma.StringNullableFilter<"Setlist"> | string | null
  duration?: Prisma.IntNullableFilter<"Setlist"> | number | null
  entries?: Prisma.SetlistEntryListRelationFilter
}

export type SetlistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  date?: Prisma.SortOrder
  location?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  entries?: Prisma.SetlistEntryOrderByRelationAggregateInput
}

export type SetlistWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.SetlistWhereInput | Prisma.SetlistWhereInput[]
  OR?: Prisma.SetlistWhereInput[]
  NOT?: Prisma.SetlistWhereInput | Prisma.SetlistWhereInput[]
  date?: Prisma.DateTimeFilter<"Setlist"> | Date | string
  location?: Prisma.StringFilter<"Setlist"> | string
  name?: Prisma.StringNullableFilter<"Setlist"> | string | null
  duration?: Prisma.IntNullableFilter<"Setlist"> | number | null
  entries?: Prisma.SetlistEntryListRelationFilter
}, "id" | "slug">

export type SetlistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  date?: Prisma.SortOrder
  location?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SetlistCountOrderByAggregateInput
  _avg?: Prisma.SetlistAvgOrderByAggregateInput
  _max?: Prisma.SetlistMaxOrderByAggregateInput
  _min?: Prisma.SetlistMinOrderByAggregateInput
  _sum?: Prisma.SetlistSumOrderByAggregateInput
}

export type SetlistScalarWhereWithAggregatesInput = {
  AND?: Prisma.SetlistScalarWhereWithAggregatesInput | Prisma.SetlistScalarWhereWithAggregatesInput[]
  OR?: Prisma.SetlistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SetlistScalarWhereWithAggregatesInput | Prisma.SetlistScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Setlist"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Setlist"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Setlist"> | Date | string
  location?: Prisma.StringWithAggregatesFilter<"Setlist"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"Setlist"> | string | null
  duration?: Prisma.IntNullableWithAggregatesFilter<"Setlist"> | number | null
}

export type SetlistCreateInput = {
  id?: string
  slug: string
  date: Date | string
  location: string
  name?: string | null
  duration?: number | null
  entries?: Prisma.SetlistEntryCreateNestedManyWithoutSetlistInput
}

export type SetlistUncheckedCreateInput = {
  id?: string
  slug: string
  date: Date | string
  location: string
  name?: string | null
  duration?: number | null
  entries?: Prisma.SetlistEntryUncheckedCreateNestedManyWithoutSetlistInput
}

export type SetlistUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  entries?: Prisma.SetlistEntryUpdateManyWithoutSetlistNestedInput
}

export type SetlistUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  entries?: Prisma.SetlistEntryUncheckedUpdateManyWithoutSetlistNestedInput
}

export type SetlistCreateManyInput = {
  id?: string
  slug: string
  date: Date | string
  location: string
  name?: string | null
  duration?: number | null
}

export type SetlistUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SetlistUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SetlistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  date?: Prisma.SortOrder
  location?: Prisma.SortOrder
  name?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type SetlistAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type SetlistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  date?: Prisma.SortOrder
  location?: Prisma.SortOrder
  name?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type SetlistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  date?: Prisma.SortOrder
  location?: Prisma.SortOrder
  name?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type SetlistSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type SetlistScalarRelationFilter = {
  is?: Prisma.SetlistWhereInput
  isNot?: Prisma.SetlistWhereInput
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type SetlistCreateNestedOneWithoutEntriesInput = {
  create?: Prisma.XOR<Prisma.SetlistCreateWithoutEntriesInput, Prisma.SetlistUncheckedCreateWithoutEntriesInput>
  connectOrCreate?: Prisma.SetlistCreateOrConnectWithoutEntriesInput
  connect?: Prisma.SetlistWhereUniqueInput
}

export type SetlistUpdateOneRequiredWithoutEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.SetlistCreateWithoutEntriesInput, Prisma.SetlistUncheckedCreateWithoutEntriesInput>
  connectOrCreate?: Prisma.SetlistCreateOrConnectWithoutEntriesInput
  upsert?: Prisma.SetlistUpsertWithoutEntriesInput
  connect?: Prisma.SetlistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SetlistUpdateToOneWithWhereWithoutEntriesInput, Prisma.SetlistUpdateWithoutEntriesInput>, Prisma.SetlistUncheckedUpdateWithoutEntriesInput>
}

export type SetlistCreateWithoutEntriesInput = {
  id?: string
  slug: string
  date: Date | string
  location: string
  name?: string | null
  duration?: number | null
}

export type SetlistUncheckedCreateWithoutEntriesInput = {
  id?: string
  slug: string
  date: Date | string
  location: string
  name?: string | null
  duration?: number | null
}

export type SetlistCreateOrConnectWithoutEntriesInput = {
  where: Prisma.SetlistWhereUniqueInput
  create: Prisma.XOR<Prisma.SetlistCreateWithoutEntriesInput, Prisma.SetlistUncheckedCreateWithoutEntriesInput>
}

export type SetlistUpsertWithoutEntriesInput = {
  update: Prisma.XOR<Prisma.SetlistUpdateWithoutEntriesInput, Prisma.SetlistUncheckedUpdateWithoutEntriesInput>
  create: Prisma.XOR<Prisma.SetlistCreateWithoutEntriesInput, Prisma.SetlistUncheckedCreateWithoutEntriesInput>
  where?: Prisma.SetlistWhereInput
}

export type SetlistUpdateToOneWithWhereWithoutEntriesInput = {
  where?: Prisma.SetlistWhereInput
  data: Prisma.XOR<Prisma.SetlistUpdateWithoutEntriesInput, Prisma.SetlistUncheckedUpdateWithoutEntriesInput>
}

export type SetlistUpdateWithoutEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SetlistUncheckedUpdateWithoutEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type SetlistCountOutputType
 */

export type SetlistCountOutputType = {
  entries: number
}

export type SetlistCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  entries?: boolean | SetlistCountOutputTypeCountEntriesArgs
}

/**
 * SetlistCountOutputType without action
 */
export type SetlistCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistCountOutputType
   */
  select?: Prisma.SetlistCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SetlistCountOutputType without action
 */
export type SetlistCountOutputTypeCountEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SetlistEntryWhereInput
}


export type SetlistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  date?: boolean
  location?: boolean
  name?: boolean
  duration?: boolean
  entries?: boolean | Prisma.Setlist$entriesArgs<ExtArgs>
  _count?: boolean | Prisma.SetlistCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setlist"]>

export type SetlistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  date?: boolean
  location?: boolean
  name?: boolean
  duration?: boolean
}, ExtArgs["result"]["setlist"]>

export type SetlistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  date?: boolean
  location?: boolean
  name?: boolean
  duration?: boolean
}, ExtArgs["result"]["setlist"]>

export type SetlistSelectScalar = {
  id?: boolean
  slug?: boolean
  date?: boolean
  location?: boolean
  name?: boolean
  duration?: boolean
}

export type SetlistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "date" | "location" | "name" | "duration", ExtArgs["result"]["setlist"]>
export type SetlistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  entries?: boolean | Prisma.Setlist$entriesArgs<ExtArgs>
  _count?: boolean | Prisma.SetlistCountOutputTypeDefaultArgs<ExtArgs>
}
export type SetlistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SetlistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SetlistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Setlist"
  objects: {
    entries: Prisma.$SetlistEntryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    slug: string
    date: Date
    location: string
    name: string | null
    duration: number | null
  }, ExtArgs["result"]["setlist"]>
  composites: {}
}

export type SetlistGetPayload<S extends boolean | null | undefined | SetlistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SetlistPayload, S>

export type SetlistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SetlistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SetlistCountAggregateInputType | true
  }

export interface SetlistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Setlist'], meta: { name: 'Setlist' } }
  /**
   * Find zero or one Setlist that matches the filter.
   * @param {SetlistFindUniqueArgs} args - Arguments to find a Setlist
   * @example
   * // Get one Setlist
   * const setlist = await prisma.setlist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SetlistFindUniqueArgs>(args: Prisma.SelectSubset<T, SetlistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Setlist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SetlistFindUniqueOrThrowArgs} args - Arguments to find a Setlist
   * @example
   * // Get one Setlist
   * const setlist = await prisma.setlist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SetlistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SetlistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Setlist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistFindFirstArgs} args - Arguments to find a Setlist
   * @example
   * // Get one Setlist
   * const setlist = await prisma.setlist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SetlistFindFirstArgs>(args?: Prisma.SelectSubset<T, SetlistFindFirstArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Setlist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistFindFirstOrThrowArgs} args - Arguments to find a Setlist
   * @example
   * // Get one Setlist
   * const setlist = await prisma.setlist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SetlistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SetlistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Setlists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Setlists
   * const setlists = await prisma.setlist.findMany()
   * 
   * // Get first 10 Setlists
   * const setlists = await prisma.setlist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const setlistWithIdOnly = await prisma.setlist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SetlistFindManyArgs>(args?: Prisma.SelectSubset<T, SetlistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Setlist.
   * @param {SetlistCreateArgs} args - Arguments to create a Setlist.
   * @example
   * // Create one Setlist
   * const Setlist = await prisma.setlist.create({
   *   data: {
   *     // ... data to create a Setlist
   *   }
   * })
   * 
   */
  create<T extends SetlistCreateArgs>(args: Prisma.SelectSubset<T, SetlistCreateArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Setlists.
   * @param {SetlistCreateManyArgs} args - Arguments to create many Setlists.
   * @example
   * // Create many Setlists
   * const setlist = await prisma.setlist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SetlistCreateManyArgs>(args?: Prisma.SelectSubset<T, SetlistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Setlists and returns the data saved in the database.
   * @param {SetlistCreateManyAndReturnArgs} args - Arguments to create many Setlists.
   * @example
   * // Create many Setlists
   * const setlist = await prisma.setlist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Setlists and only return the `id`
   * const setlistWithIdOnly = await prisma.setlist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SetlistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SetlistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Setlist.
   * @param {SetlistDeleteArgs} args - Arguments to delete one Setlist.
   * @example
   * // Delete one Setlist
   * const Setlist = await prisma.setlist.delete({
   *   where: {
   *     // ... filter to delete one Setlist
   *   }
   * })
   * 
   */
  delete<T extends SetlistDeleteArgs>(args: Prisma.SelectSubset<T, SetlistDeleteArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Setlist.
   * @param {SetlistUpdateArgs} args - Arguments to update one Setlist.
   * @example
   * // Update one Setlist
   * const setlist = await prisma.setlist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SetlistUpdateArgs>(args: Prisma.SelectSubset<T, SetlistUpdateArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Setlists.
   * @param {SetlistDeleteManyArgs} args - Arguments to filter Setlists to delete.
   * @example
   * // Delete a few Setlists
   * const { count } = await prisma.setlist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SetlistDeleteManyArgs>(args?: Prisma.SelectSubset<T, SetlistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Setlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Setlists
   * const setlist = await prisma.setlist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SetlistUpdateManyArgs>(args: Prisma.SelectSubset<T, SetlistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Setlists and returns the data updated in the database.
   * @param {SetlistUpdateManyAndReturnArgs} args - Arguments to update many Setlists.
   * @example
   * // Update many Setlists
   * const setlist = await prisma.setlist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Setlists and only return the `id`
   * const setlistWithIdOnly = await prisma.setlist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SetlistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SetlistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Setlist.
   * @param {SetlistUpsertArgs} args - Arguments to update or create a Setlist.
   * @example
   * // Update or create a Setlist
   * const setlist = await prisma.setlist.upsert({
   *   create: {
   *     // ... data to create a Setlist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Setlist we want to update
   *   }
   * })
   */
  upsert<T extends SetlistUpsertArgs>(args: Prisma.SelectSubset<T, SetlistUpsertArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Setlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistCountArgs} args - Arguments to filter Setlists to count.
   * @example
   * // Count the number of Setlists
   * const count = await prisma.setlist.count({
   *   where: {
   *     // ... the filter for the Setlists we want to count
   *   }
   * })
  **/
  count<T extends SetlistCountArgs>(
    args?: Prisma.Subset<T, SetlistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SetlistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Setlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SetlistAggregateArgs>(args: Prisma.Subset<T, SetlistAggregateArgs>): Prisma.PrismaPromise<GetSetlistAggregateType<T>>

  /**
   * Group by Setlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SetlistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SetlistGroupByArgs['orderBy'] }
      : { orderBy?: SetlistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SetlistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSetlistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Setlist model
 */
readonly fields: SetlistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Setlist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SetlistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  entries<T extends Prisma.Setlist$entriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Setlist$entriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Setlist model
 */
export interface SetlistFieldRefs {
  readonly id: Prisma.FieldRef<"Setlist", 'String'>
  readonly slug: Prisma.FieldRef<"Setlist", 'String'>
  readonly date: Prisma.FieldRef<"Setlist", 'DateTime'>
  readonly location: Prisma.FieldRef<"Setlist", 'String'>
  readonly name: Prisma.FieldRef<"Setlist", 'String'>
  readonly duration: Prisma.FieldRef<"Setlist", 'Int'>
}
    

// Custom InputTypes
/**
 * Setlist findUnique
 */
export type SetlistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * Filter, which Setlist to fetch.
   */
  where: Prisma.SetlistWhereUniqueInput
}

/**
 * Setlist findUniqueOrThrow
 */
export type SetlistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * Filter, which Setlist to fetch.
   */
  where: Prisma.SetlistWhereUniqueInput
}

/**
 * Setlist findFirst
 */
export type SetlistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * Filter, which Setlist to fetch.
   */
  where?: Prisma.SetlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Setlists to fetch.
   */
  orderBy?: Prisma.SetlistOrderByWithRelationInput | Prisma.SetlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Setlists.
   */
  cursor?: Prisma.SetlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Setlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Setlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Setlists.
   */
  distinct?: Prisma.SetlistScalarFieldEnum | Prisma.SetlistScalarFieldEnum[]
}

/**
 * Setlist findFirstOrThrow
 */
export type SetlistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * Filter, which Setlist to fetch.
   */
  where?: Prisma.SetlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Setlists to fetch.
   */
  orderBy?: Prisma.SetlistOrderByWithRelationInput | Prisma.SetlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Setlists.
   */
  cursor?: Prisma.SetlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Setlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Setlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Setlists.
   */
  distinct?: Prisma.SetlistScalarFieldEnum | Prisma.SetlistScalarFieldEnum[]
}

/**
 * Setlist findMany
 */
export type SetlistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * Filter, which Setlists to fetch.
   */
  where?: Prisma.SetlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Setlists to fetch.
   */
  orderBy?: Prisma.SetlistOrderByWithRelationInput | Prisma.SetlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Setlists.
   */
  cursor?: Prisma.SetlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Setlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Setlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Setlists.
   */
  distinct?: Prisma.SetlistScalarFieldEnum | Prisma.SetlistScalarFieldEnum[]
}

/**
 * Setlist create
 */
export type SetlistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * The data needed to create a Setlist.
   */
  data: Prisma.XOR<Prisma.SetlistCreateInput, Prisma.SetlistUncheckedCreateInput>
}

/**
 * Setlist createMany
 */
export type SetlistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Setlists.
   */
  data: Prisma.SetlistCreateManyInput | Prisma.SetlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Setlist createManyAndReturn
 */
export type SetlistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * The data used to create many Setlists.
   */
  data: Prisma.SetlistCreateManyInput | Prisma.SetlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Setlist update
 */
export type SetlistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * The data needed to update a Setlist.
   */
  data: Prisma.XOR<Prisma.SetlistUpdateInput, Prisma.SetlistUncheckedUpdateInput>
  /**
   * Choose, which Setlist to update.
   */
  where: Prisma.SetlistWhereUniqueInput
}

/**
 * Setlist updateMany
 */
export type SetlistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Setlists.
   */
  data: Prisma.XOR<Prisma.SetlistUpdateManyMutationInput, Prisma.SetlistUncheckedUpdateManyInput>
  /**
   * Filter which Setlists to update
   */
  where?: Prisma.SetlistWhereInput
  /**
   * Limit how many Setlists to update.
   */
  limit?: number
}

/**
 * Setlist updateManyAndReturn
 */
export type SetlistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * The data used to update Setlists.
   */
  data: Prisma.XOR<Prisma.SetlistUpdateManyMutationInput, Prisma.SetlistUncheckedUpdateManyInput>
  /**
   * Filter which Setlists to update
   */
  where?: Prisma.SetlistWhereInput
  /**
   * Limit how many Setlists to update.
   */
  limit?: number
}

/**
 * Setlist upsert
 */
export type SetlistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * The filter to search for the Setlist to update in case it exists.
   */
  where: Prisma.SetlistWhereUniqueInput
  /**
   * In case the Setlist found by the `where` argument doesn't exist, create a new Setlist with this data.
   */
  create: Prisma.XOR<Prisma.SetlistCreateInput, Prisma.SetlistUncheckedCreateInput>
  /**
   * In case the Setlist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SetlistUpdateInput, Prisma.SetlistUncheckedUpdateInput>
}

/**
 * Setlist delete
 */
export type SetlistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
  /**
   * Filter which Setlist to delete.
   */
  where: Prisma.SetlistWhereUniqueInput
}

/**
 * Setlist deleteMany
 */
export type SetlistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Setlists to delete
   */
  where?: Prisma.SetlistWhereInput
  /**
   * Limit how many Setlists to delete.
   */
  limit?: number
}

/**
 * Setlist.entries
 */
export type Setlist$entriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  where?: Prisma.SetlistEntryWhereInput
  orderBy?: Prisma.SetlistEntryOrderByWithRelationInput | Prisma.SetlistEntryOrderByWithRelationInput[]
  cursor?: Prisma.SetlistEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SetlistEntryScalarFieldEnum | Prisma.SetlistEntryScalarFieldEnum[]
}

/**
 * Setlist without action
 */
export type SetlistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Setlist
   */
  select?: Prisma.SetlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Setlist
   */
  omit?: Prisma.SetlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistInclude<ExtArgs> | null
}
