
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SetlistEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SetlistEntry
 * 
 */
export type SetlistEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$SetlistEntryPayload>

export type AggregateSetlistEntry = {
  _count: SetlistEntryCountAggregateOutputType | null
  _avg: SetlistEntryAvgAggregateOutputType | null
  _sum: SetlistEntrySumAggregateOutputType | null
  _min: SetlistEntryMinAggregateOutputType | null
  _max: SetlistEntryMaxAggregateOutputType | null
}

export type SetlistEntryAvgAggregateOutputType = {
  position: number | null
}

export type SetlistEntrySumAggregateOutputType = {
  position: number | null
}

export type SetlistEntryMinAggregateOutputType = {
  id: string | null
  position: number | null
  isOptional: boolean | null
  isEncore: boolean | null
  setlistId: string | null
  songId: string | null
}

export type SetlistEntryMaxAggregateOutputType = {
  id: string | null
  position: number | null
  isOptional: boolean | null
  isEncore: boolean | null
  setlistId: string | null
  songId: string | null
}

export type SetlistEntryCountAggregateOutputType = {
  id: number
  position: number
  isOptional: number
  isEncore: number
  setlistId: number
  songId: number
  _all: number
}


export type SetlistEntryAvgAggregateInputType = {
  position?: true
}

export type SetlistEntrySumAggregateInputType = {
  position?: true
}

export type SetlistEntryMinAggregateInputType = {
  id?: true
  position?: true
  isOptional?: true
  isEncore?: true
  setlistId?: true
  songId?: true
}

export type SetlistEntryMaxAggregateInputType = {
  id?: true
  position?: true
  isOptional?: true
  isEncore?: true
  setlistId?: true
  songId?: true
}

export type SetlistEntryCountAggregateInputType = {
  id?: true
  position?: true
  isOptional?: true
  isEncore?: true
  setlistId?: true
  songId?: true
  _all?: true
}

export type SetlistEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SetlistEntry to aggregate.
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetlistEntries to fetch.
   */
  orderBy?: Prisma.SetlistEntryOrderByWithRelationInput | Prisma.SetlistEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SetlistEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetlistEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetlistEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SetlistEntries
  **/
  _count?: true | SetlistEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SetlistEntryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SetlistEntrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SetlistEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SetlistEntryMaxAggregateInputType
}

export type GetSetlistEntryAggregateType<T extends SetlistEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateSetlistEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSetlistEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateSetlistEntry[P]>
}




export type SetlistEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SetlistEntryWhereInput
  orderBy?: Prisma.SetlistEntryOrderByWithAggregationInput | Prisma.SetlistEntryOrderByWithAggregationInput[]
  by: Prisma.SetlistEntryScalarFieldEnum[] | Prisma.SetlistEntryScalarFieldEnum
  having?: Prisma.SetlistEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SetlistEntryCountAggregateInputType | true
  _avg?: SetlistEntryAvgAggregateInputType
  _sum?: SetlistEntrySumAggregateInputType
  _min?: SetlistEntryMinAggregateInputType
  _max?: SetlistEntryMaxAggregateInputType
}

export type SetlistEntryGroupByOutputType = {
  id: string
  position: number
  isOptional: boolean
  isEncore: boolean
  setlistId: string
  songId: string
  _count: SetlistEntryCountAggregateOutputType | null
  _avg: SetlistEntryAvgAggregateOutputType | null
  _sum: SetlistEntrySumAggregateOutputType | null
  _min: SetlistEntryMinAggregateOutputType | null
  _max: SetlistEntryMaxAggregateOutputType | null
}

export type GetSetlistEntryGroupByPayload<T extends SetlistEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SetlistEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SetlistEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SetlistEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SetlistEntryGroupByOutputType[P]>
      }
    >
  >



export type SetlistEntryWhereInput = {
  AND?: Prisma.SetlistEntryWhereInput | Prisma.SetlistEntryWhereInput[]
  OR?: Prisma.SetlistEntryWhereInput[]
  NOT?: Prisma.SetlistEntryWhereInput | Prisma.SetlistEntryWhereInput[]
  id?: Prisma.StringFilter<"SetlistEntry"> | string
  position?: Prisma.IntFilter<"SetlistEntry"> | number
  isOptional?: Prisma.BoolFilter<"SetlistEntry"> | boolean
  isEncore?: Prisma.BoolFilter<"SetlistEntry"> | boolean
  setlistId?: Prisma.StringFilter<"SetlistEntry"> | string
  songId?: Prisma.StringFilter<"SetlistEntry"> | string
  setlist?: Prisma.XOR<Prisma.SetlistScalarRelationFilter, Prisma.SetlistWhereInput>
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
}

export type SetlistEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isOptional?: Prisma.SortOrder
  isEncore?: Prisma.SortOrder
  setlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  setlist?: Prisma.SetlistOrderByWithRelationInput
  song?: Prisma.SongOrderByWithRelationInput
}

export type SetlistEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SetlistEntryWhereInput | Prisma.SetlistEntryWhereInput[]
  OR?: Prisma.SetlistEntryWhereInput[]
  NOT?: Prisma.SetlistEntryWhereInput | Prisma.SetlistEntryWhereInput[]
  position?: Prisma.IntFilter<"SetlistEntry"> | number
  isOptional?: Prisma.BoolFilter<"SetlistEntry"> | boolean
  isEncore?: Prisma.BoolFilter<"SetlistEntry"> | boolean
  setlistId?: Prisma.StringFilter<"SetlistEntry"> | string
  songId?: Prisma.StringFilter<"SetlistEntry"> | string
  setlist?: Prisma.XOR<Prisma.SetlistScalarRelationFilter, Prisma.SetlistWhereInput>
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
}, "id">

export type SetlistEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isOptional?: Prisma.SortOrder
  isEncore?: Prisma.SortOrder
  setlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  _count?: Prisma.SetlistEntryCountOrderByAggregateInput
  _avg?: Prisma.SetlistEntryAvgOrderByAggregateInput
  _max?: Prisma.SetlistEntryMaxOrderByAggregateInput
  _min?: Prisma.SetlistEntryMinOrderByAggregateInput
  _sum?: Prisma.SetlistEntrySumOrderByAggregateInput
}

export type SetlistEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.SetlistEntryScalarWhereWithAggregatesInput | Prisma.SetlistEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.SetlistEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SetlistEntryScalarWhereWithAggregatesInput | Prisma.SetlistEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SetlistEntry"> | string
  position?: Prisma.IntWithAggregatesFilter<"SetlistEntry"> | number
  isOptional?: Prisma.BoolWithAggregatesFilter<"SetlistEntry"> | boolean
  isEncore?: Prisma.BoolWithAggregatesFilter<"SetlistEntry"> | boolean
  setlistId?: Prisma.StringWithAggregatesFilter<"SetlistEntry"> | string
  songId?: Prisma.StringWithAggregatesFilter<"SetlistEntry"> | string
}

export type SetlistEntryCreateInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  setlist: Prisma.SetlistCreateNestedOneWithoutEntriesInput
  song: Prisma.SongCreateNestedOneWithoutEntriesInput
}

export type SetlistEntryUncheckedCreateInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  setlistId: string
  songId: string
}

export type SetlistEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  setlist?: Prisma.SetlistUpdateOneRequiredWithoutEntriesNestedInput
  song?: Prisma.SongUpdateOneRequiredWithoutEntriesNestedInput
}

export type SetlistEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  setlistId?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SetlistEntryCreateManyInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  setlistId: string
  songId: string
}

export type SetlistEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SetlistEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  setlistId?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SetlistEntryListRelationFilter = {
  every?: Prisma.SetlistEntryWhereInput
  some?: Prisma.SetlistEntryWhereInput
  none?: Prisma.SetlistEntryWhereInput
}

export type SetlistEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SetlistEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isOptional?: Prisma.SortOrder
  isEncore?: Prisma.SortOrder
  setlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
}

export type SetlistEntryAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type SetlistEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isOptional?: Prisma.SortOrder
  isEncore?: Prisma.SortOrder
  setlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
}

export type SetlistEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isOptional?: Prisma.SortOrder
  isEncore?: Prisma.SortOrder
  setlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
}

export type SetlistEntrySumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type SetlistEntryCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSongInput, Prisma.SetlistEntryUncheckedCreateWithoutSongInput> | Prisma.SetlistEntryCreateWithoutSongInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSongInput | Prisma.SetlistEntryCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.SetlistEntryCreateManySongInputEnvelope
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
}

export type SetlistEntryUncheckedCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSongInput, Prisma.SetlistEntryUncheckedCreateWithoutSongInput> | Prisma.SetlistEntryCreateWithoutSongInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSongInput | Prisma.SetlistEntryCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.SetlistEntryCreateManySongInputEnvelope
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
}

export type SetlistEntryUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSongInput, Prisma.SetlistEntryUncheckedCreateWithoutSongInput> | Prisma.SetlistEntryCreateWithoutSongInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSongInput | Prisma.SetlistEntryCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSongInput | Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.SetlistEntryCreateManySongInputEnvelope
  set?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  disconnect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  delete?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  update?: Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSongInput | Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.SetlistEntryUpdateManyWithWhereWithoutSongInput | Prisma.SetlistEntryUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.SetlistEntryScalarWhereInput | Prisma.SetlistEntryScalarWhereInput[]
}

export type SetlistEntryUncheckedUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSongInput, Prisma.SetlistEntryUncheckedCreateWithoutSongInput> | Prisma.SetlistEntryCreateWithoutSongInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSongInput | Prisma.SetlistEntryCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSongInput | Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.SetlistEntryCreateManySongInputEnvelope
  set?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  disconnect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  delete?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  update?: Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSongInput | Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.SetlistEntryUpdateManyWithWhereWithoutSongInput | Prisma.SetlistEntryUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.SetlistEntryScalarWhereInput | Prisma.SetlistEntryScalarWhereInput[]
}

export type SetlistEntryCreateNestedManyWithoutSetlistInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSetlistInput, Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput> | Prisma.SetlistEntryCreateWithoutSetlistInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput | Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput[]
  createMany?: Prisma.SetlistEntryCreateManySetlistInputEnvelope
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
}

export type SetlistEntryUncheckedCreateNestedManyWithoutSetlistInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSetlistInput, Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput> | Prisma.SetlistEntryCreateWithoutSetlistInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput | Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput[]
  createMany?: Prisma.SetlistEntryCreateManySetlistInputEnvelope
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
}

export type SetlistEntryUpdateManyWithoutSetlistNestedInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSetlistInput, Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput> | Prisma.SetlistEntryCreateWithoutSetlistInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput | Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput[]
  upsert?: Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSetlistInput | Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSetlistInput[]
  createMany?: Prisma.SetlistEntryCreateManySetlistInputEnvelope
  set?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  disconnect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  delete?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  update?: Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSetlistInput | Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSetlistInput[]
  updateMany?: Prisma.SetlistEntryUpdateManyWithWhereWithoutSetlistInput | Prisma.SetlistEntryUpdateManyWithWhereWithoutSetlistInput[]
  deleteMany?: Prisma.SetlistEntryScalarWhereInput | Prisma.SetlistEntryScalarWhereInput[]
}

export type SetlistEntryUncheckedUpdateManyWithoutSetlistNestedInput = {
  create?: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSetlistInput, Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput> | Prisma.SetlistEntryCreateWithoutSetlistInput[] | Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput[]
  connectOrCreate?: Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput | Prisma.SetlistEntryCreateOrConnectWithoutSetlistInput[]
  upsert?: Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSetlistInput | Prisma.SetlistEntryUpsertWithWhereUniqueWithoutSetlistInput[]
  createMany?: Prisma.SetlistEntryCreateManySetlistInputEnvelope
  set?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  disconnect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  delete?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  connect?: Prisma.SetlistEntryWhereUniqueInput | Prisma.SetlistEntryWhereUniqueInput[]
  update?: Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSetlistInput | Prisma.SetlistEntryUpdateWithWhereUniqueWithoutSetlistInput[]
  updateMany?: Prisma.SetlistEntryUpdateManyWithWhereWithoutSetlistInput | Prisma.SetlistEntryUpdateManyWithWhereWithoutSetlistInput[]
  deleteMany?: Prisma.SetlistEntryScalarWhereInput | Prisma.SetlistEntryScalarWhereInput[]
}

export type SetlistEntryCreateWithoutSongInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  setlist: Prisma.SetlistCreateNestedOneWithoutEntriesInput
}

export type SetlistEntryUncheckedCreateWithoutSongInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  setlistId: string
}

export type SetlistEntryCreateOrConnectWithoutSongInput = {
  where: Prisma.SetlistEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSongInput, Prisma.SetlistEntryUncheckedCreateWithoutSongInput>
}

export type SetlistEntryCreateManySongInputEnvelope = {
  data: Prisma.SetlistEntryCreateManySongInput | Prisma.SetlistEntryCreateManySongInput[]
}

export type SetlistEntryUpsertWithWhereUniqueWithoutSongInput = {
  where: Prisma.SetlistEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.SetlistEntryUpdateWithoutSongInput, Prisma.SetlistEntryUncheckedUpdateWithoutSongInput>
  create: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSongInput, Prisma.SetlistEntryUncheckedCreateWithoutSongInput>
}

export type SetlistEntryUpdateWithWhereUniqueWithoutSongInput = {
  where: Prisma.SetlistEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.SetlistEntryUpdateWithoutSongInput, Prisma.SetlistEntryUncheckedUpdateWithoutSongInput>
}

export type SetlistEntryUpdateManyWithWhereWithoutSongInput = {
  where: Prisma.SetlistEntryScalarWhereInput
  data: Prisma.XOR<Prisma.SetlistEntryUpdateManyMutationInput, Prisma.SetlistEntryUncheckedUpdateManyWithoutSongInput>
}

export type SetlistEntryScalarWhereInput = {
  AND?: Prisma.SetlistEntryScalarWhereInput | Prisma.SetlistEntryScalarWhereInput[]
  OR?: Prisma.SetlistEntryScalarWhereInput[]
  NOT?: Prisma.SetlistEntryScalarWhereInput | Prisma.SetlistEntryScalarWhereInput[]
  id?: Prisma.StringFilter<"SetlistEntry"> | string
  position?: Prisma.IntFilter<"SetlistEntry"> | number
  isOptional?: Prisma.BoolFilter<"SetlistEntry"> | boolean
  isEncore?: Prisma.BoolFilter<"SetlistEntry"> | boolean
  setlistId?: Prisma.StringFilter<"SetlistEntry"> | string
  songId?: Prisma.StringFilter<"SetlistEntry"> | string
}

export type SetlistEntryCreateWithoutSetlistInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  song: Prisma.SongCreateNestedOneWithoutEntriesInput
}

export type SetlistEntryUncheckedCreateWithoutSetlistInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  songId: string
}

export type SetlistEntryCreateOrConnectWithoutSetlistInput = {
  where: Prisma.SetlistEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSetlistInput, Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput>
}

export type SetlistEntryCreateManySetlistInputEnvelope = {
  data: Prisma.SetlistEntryCreateManySetlistInput | Prisma.SetlistEntryCreateManySetlistInput[]
}

export type SetlistEntryUpsertWithWhereUniqueWithoutSetlistInput = {
  where: Prisma.SetlistEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.SetlistEntryUpdateWithoutSetlistInput, Prisma.SetlistEntryUncheckedUpdateWithoutSetlistInput>
  create: Prisma.XOR<Prisma.SetlistEntryCreateWithoutSetlistInput, Prisma.SetlistEntryUncheckedCreateWithoutSetlistInput>
}

export type SetlistEntryUpdateWithWhereUniqueWithoutSetlistInput = {
  where: Prisma.SetlistEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.SetlistEntryUpdateWithoutSetlistInput, Prisma.SetlistEntryUncheckedUpdateWithoutSetlistInput>
}

export type SetlistEntryUpdateManyWithWhereWithoutSetlistInput = {
  where: Prisma.SetlistEntryScalarWhereInput
  data: Prisma.XOR<Prisma.SetlistEntryUpdateManyMutationInput, Prisma.SetlistEntryUncheckedUpdateManyWithoutSetlistInput>
}

export type SetlistEntryCreateManySongInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  setlistId: string
}

export type SetlistEntryUpdateWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  setlist?: Prisma.SetlistUpdateOneRequiredWithoutEntriesNestedInput
}

export type SetlistEntryUncheckedUpdateWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  setlistId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SetlistEntryUncheckedUpdateManyWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  setlistId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SetlistEntryCreateManySetlistInput = {
  id?: string
  position: number
  isOptional?: boolean
  isEncore?: boolean
  songId: string
}

export type SetlistEntryUpdateWithoutSetlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  song?: Prisma.SongUpdateOneRequiredWithoutEntriesNestedInput
}

export type SetlistEntryUncheckedUpdateWithoutSetlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SetlistEntryUncheckedUpdateManyWithoutSetlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isOptional?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isEncore?: Prisma.BoolFieldUpdateOperationsInput | boolean
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SetlistEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  position?: boolean
  isOptional?: boolean
  isEncore?: boolean
  setlistId?: boolean
  songId?: boolean
  setlist?: boolean | Prisma.SetlistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setlistEntry"]>

export type SetlistEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  position?: boolean
  isOptional?: boolean
  isEncore?: boolean
  setlistId?: boolean
  songId?: boolean
  setlist?: boolean | Prisma.SetlistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setlistEntry"]>

export type SetlistEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  position?: boolean
  isOptional?: boolean
  isEncore?: boolean
  setlistId?: boolean
  songId?: boolean
  setlist?: boolean | Prisma.SetlistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["setlistEntry"]>

export type SetlistEntrySelectScalar = {
  id?: boolean
  position?: boolean
  isOptional?: boolean
  isEncore?: boolean
  setlistId?: boolean
  songId?: boolean
}

export type SetlistEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "position" | "isOptional" | "isEncore" | "setlistId" | "songId", ExtArgs["result"]["setlistEntry"]>
export type SetlistEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  setlist?: boolean | Prisma.SetlistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}
export type SetlistEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  setlist?: boolean | Prisma.SetlistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}
export type SetlistEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  setlist?: boolean | Prisma.SetlistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}

export type $SetlistEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SetlistEntry"
  objects: {
    setlist: Prisma.$SetlistPayload<ExtArgs>
    song: Prisma.$SongPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    position: number
    isOptional: boolean
    isEncore: boolean
    setlistId: string
    songId: string
  }, ExtArgs["result"]["setlistEntry"]>
  composites: {}
}

export type SetlistEntryGetPayload<S extends boolean | null | undefined | SetlistEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload, S>

export type SetlistEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SetlistEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SetlistEntryCountAggregateInputType | true
  }

export interface SetlistEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SetlistEntry'], meta: { name: 'SetlistEntry' } }
  /**
   * Find zero or one SetlistEntry that matches the filter.
   * @param {SetlistEntryFindUniqueArgs} args - Arguments to find a SetlistEntry
   * @example
   * // Get one SetlistEntry
   * const setlistEntry = await prisma.setlistEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SetlistEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, SetlistEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SetlistEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SetlistEntryFindUniqueOrThrowArgs} args - Arguments to find a SetlistEntry
   * @example
   * // Get one SetlistEntry
   * const setlistEntry = await prisma.setlistEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SetlistEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SetlistEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SetlistEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryFindFirstArgs} args - Arguments to find a SetlistEntry
   * @example
   * // Get one SetlistEntry
   * const setlistEntry = await prisma.setlistEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SetlistEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, SetlistEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SetlistEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryFindFirstOrThrowArgs} args - Arguments to find a SetlistEntry
   * @example
   * // Get one SetlistEntry
   * const setlistEntry = await prisma.setlistEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SetlistEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SetlistEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SetlistEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SetlistEntries
   * const setlistEntries = await prisma.setlistEntry.findMany()
   * 
   * // Get first 10 SetlistEntries
   * const setlistEntries = await prisma.setlistEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const setlistEntryWithIdOnly = await prisma.setlistEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SetlistEntryFindManyArgs>(args?: Prisma.SelectSubset<T, SetlistEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SetlistEntry.
   * @param {SetlistEntryCreateArgs} args - Arguments to create a SetlistEntry.
   * @example
   * // Create one SetlistEntry
   * const SetlistEntry = await prisma.setlistEntry.create({
   *   data: {
   *     // ... data to create a SetlistEntry
   *   }
   * })
   * 
   */
  create<T extends SetlistEntryCreateArgs>(args: Prisma.SelectSubset<T, SetlistEntryCreateArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SetlistEntries.
   * @param {SetlistEntryCreateManyArgs} args - Arguments to create many SetlistEntries.
   * @example
   * // Create many SetlistEntries
   * const setlistEntry = await prisma.setlistEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SetlistEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, SetlistEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SetlistEntries and returns the data saved in the database.
   * @param {SetlistEntryCreateManyAndReturnArgs} args - Arguments to create many SetlistEntries.
   * @example
   * // Create many SetlistEntries
   * const setlistEntry = await prisma.setlistEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SetlistEntries and only return the `id`
   * const setlistEntryWithIdOnly = await prisma.setlistEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SetlistEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SetlistEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SetlistEntry.
   * @param {SetlistEntryDeleteArgs} args - Arguments to delete one SetlistEntry.
   * @example
   * // Delete one SetlistEntry
   * const SetlistEntry = await prisma.setlistEntry.delete({
   *   where: {
   *     // ... filter to delete one SetlistEntry
   *   }
   * })
   * 
   */
  delete<T extends SetlistEntryDeleteArgs>(args: Prisma.SelectSubset<T, SetlistEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SetlistEntry.
   * @param {SetlistEntryUpdateArgs} args - Arguments to update one SetlistEntry.
   * @example
   * // Update one SetlistEntry
   * const setlistEntry = await prisma.setlistEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SetlistEntryUpdateArgs>(args: Prisma.SelectSubset<T, SetlistEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SetlistEntries.
   * @param {SetlistEntryDeleteManyArgs} args - Arguments to filter SetlistEntries to delete.
   * @example
   * // Delete a few SetlistEntries
   * const { count } = await prisma.setlistEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SetlistEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, SetlistEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SetlistEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SetlistEntries
   * const setlistEntry = await prisma.setlistEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SetlistEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, SetlistEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SetlistEntries and returns the data updated in the database.
   * @param {SetlistEntryUpdateManyAndReturnArgs} args - Arguments to update many SetlistEntries.
   * @example
   * // Update many SetlistEntries
   * const setlistEntry = await prisma.setlistEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SetlistEntries and only return the `id`
   * const setlistEntryWithIdOnly = await prisma.setlistEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SetlistEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SetlistEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SetlistEntry.
   * @param {SetlistEntryUpsertArgs} args - Arguments to update or create a SetlistEntry.
   * @example
   * // Update or create a SetlistEntry
   * const setlistEntry = await prisma.setlistEntry.upsert({
   *   create: {
   *     // ... data to create a SetlistEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SetlistEntry we want to update
   *   }
   * })
   */
  upsert<T extends SetlistEntryUpsertArgs>(args: Prisma.SelectSubset<T, SetlistEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__SetlistEntryClient<runtime.Types.Result.GetResult<Prisma.$SetlistEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SetlistEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryCountArgs} args - Arguments to filter SetlistEntries to count.
   * @example
   * // Count the number of SetlistEntries
   * const count = await prisma.setlistEntry.count({
   *   where: {
   *     // ... the filter for the SetlistEntries we want to count
   *   }
   * })
  **/
  count<T extends SetlistEntryCountArgs>(
    args?: Prisma.Subset<T, SetlistEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SetlistEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SetlistEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SetlistEntryAggregateArgs>(args: Prisma.Subset<T, SetlistEntryAggregateArgs>): Prisma.PrismaPromise<GetSetlistEntryAggregateType<T>>

  /**
   * Group by SetlistEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SetlistEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SetlistEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SetlistEntryGroupByArgs['orderBy'] }
      : { orderBy?: SetlistEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SetlistEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSetlistEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SetlistEntry model
 */
readonly fields: SetlistEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SetlistEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SetlistEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  setlist<T extends Prisma.SetlistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SetlistDefaultArgs<ExtArgs>>): Prisma.Prisma__SetlistClient<runtime.Types.Result.GetResult<Prisma.$SetlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  song<T extends Prisma.SongDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SongDefaultArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SetlistEntry model
 */
export interface SetlistEntryFieldRefs {
  readonly id: Prisma.FieldRef<"SetlistEntry", 'String'>
  readonly position: Prisma.FieldRef<"SetlistEntry", 'Int'>
  readonly isOptional: Prisma.FieldRef<"SetlistEntry", 'Boolean'>
  readonly isEncore: Prisma.FieldRef<"SetlistEntry", 'Boolean'>
  readonly setlistId: Prisma.FieldRef<"SetlistEntry", 'String'>
  readonly songId: Prisma.FieldRef<"SetlistEntry", 'String'>
}
    

// Custom InputTypes
/**
 * SetlistEntry findUnique
 */
export type SetlistEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * Filter, which SetlistEntry to fetch.
   */
  where: Prisma.SetlistEntryWhereUniqueInput
}

/**
 * SetlistEntry findUniqueOrThrow
 */
export type SetlistEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * Filter, which SetlistEntry to fetch.
   */
  where: Prisma.SetlistEntryWhereUniqueInput
}

/**
 * SetlistEntry findFirst
 */
export type SetlistEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * Filter, which SetlistEntry to fetch.
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetlistEntries to fetch.
   */
  orderBy?: Prisma.SetlistEntryOrderByWithRelationInput | Prisma.SetlistEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SetlistEntries.
   */
  cursor?: Prisma.SetlistEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetlistEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetlistEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetlistEntries.
   */
  distinct?: Prisma.SetlistEntryScalarFieldEnum | Prisma.SetlistEntryScalarFieldEnum[]
}

/**
 * SetlistEntry findFirstOrThrow
 */
export type SetlistEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * Filter, which SetlistEntry to fetch.
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetlistEntries to fetch.
   */
  orderBy?: Prisma.SetlistEntryOrderByWithRelationInput | Prisma.SetlistEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SetlistEntries.
   */
  cursor?: Prisma.SetlistEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetlistEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetlistEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetlistEntries.
   */
  distinct?: Prisma.SetlistEntryScalarFieldEnum | Prisma.SetlistEntryScalarFieldEnum[]
}

/**
 * SetlistEntry findMany
 */
export type SetlistEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * Filter, which SetlistEntries to fetch.
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SetlistEntries to fetch.
   */
  orderBy?: Prisma.SetlistEntryOrderByWithRelationInput | Prisma.SetlistEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SetlistEntries.
   */
  cursor?: Prisma.SetlistEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SetlistEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SetlistEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SetlistEntries.
   */
  distinct?: Prisma.SetlistEntryScalarFieldEnum | Prisma.SetlistEntryScalarFieldEnum[]
}

/**
 * SetlistEntry create
 */
export type SetlistEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a SetlistEntry.
   */
  data: Prisma.XOR<Prisma.SetlistEntryCreateInput, Prisma.SetlistEntryUncheckedCreateInput>
}

/**
 * SetlistEntry createMany
 */
export type SetlistEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SetlistEntries.
   */
  data: Prisma.SetlistEntryCreateManyInput | Prisma.SetlistEntryCreateManyInput[]
}

/**
 * SetlistEntry createManyAndReturn
 */
export type SetlistEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * The data used to create many SetlistEntries.
   */
  data: Prisma.SetlistEntryCreateManyInput | Prisma.SetlistEntryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SetlistEntry update
 */
export type SetlistEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a SetlistEntry.
   */
  data: Prisma.XOR<Prisma.SetlistEntryUpdateInput, Prisma.SetlistEntryUncheckedUpdateInput>
  /**
   * Choose, which SetlistEntry to update.
   */
  where: Prisma.SetlistEntryWhereUniqueInput
}

/**
 * SetlistEntry updateMany
 */
export type SetlistEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SetlistEntries.
   */
  data: Prisma.XOR<Prisma.SetlistEntryUpdateManyMutationInput, Prisma.SetlistEntryUncheckedUpdateManyInput>
  /**
   * Filter which SetlistEntries to update
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * Limit how many SetlistEntries to update.
   */
  limit?: number
}

/**
 * SetlistEntry updateManyAndReturn
 */
export type SetlistEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * The data used to update SetlistEntries.
   */
  data: Prisma.XOR<Prisma.SetlistEntryUpdateManyMutationInput, Prisma.SetlistEntryUncheckedUpdateManyInput>
  /**
   * Filter which SetlistEntries to update
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * Limit how many SetlistEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SetlistEntry upsert
 */
export type SetlistEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the SetlistEntry to update in case it exists.
   */
  where: Prisma.SetlistEntryWhereUniqueInput
  /**
   * In case the SetlistEntry found by the `where` argument doesn't exist, create a new SetlistEntry with this data.
   */
  create: Prisma.XOR<Prisma.SetlistEntryCreateInput, Prisma.SetlistEntryUncheckedCreateInput>
  /**
   * In case the SetlistEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SetlistEntryUpdateInput, Prisma.SetlistEntryUncheckedUpdateInput>
}

/**
 * SetlistEntry delete
 */
export type SetlistEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
  /**
   * Filter which SetlistEntry to delete.
   */
  where: Prisma.SetlistEntryWhereUniqueInput
}

/**
 * SetlistEntry deleteMany
 */
export type SetlistEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SetlistEntries to delete
   */
  where?: Prisma.SetlistEntryWhereInput
  /**
   * Limit how many SetlistEntries to delete.
   */
  limit?: number
}

/**
 * SetlistEntry without action
 */
export type SetlistEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SetlistEntry
   */
  select?: Prisma.SetlistEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SetlistEntry
   */
  omit?: Prisma.SetlistEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SetlistEntryInclude<ExtArgs> | null
}
